[buildPlans.iosevka-mayukai-firastorm]
family = "Iosevka Mayukai Firastorm"
spacing = "term"
serifs = "sans"
no-cv-ss = false
no-ligation = false
webfont-formats = ['woff2']

###################################################################################################
# Configure variants

[buildPlans.iosevka-mayukai-firastorm.variants]
inherits = "ss05"

[buildPlans.iosevka-mayukai-firastorm.variants.design]
f = 'serifless'
r = 'corner-hooked-base-serifed'
zero = 'oval-reverse-slashed'
one = 'base-long-top-serif'
eight = 'two-circles'
asterisk = 'penta-low'
brace = 'curly-flat-boundary'
number-sign = 'upright-tall'
at = 'threefold-tall'
paren = 'large-contour'
percent = 'rings-segmented-slash'
underscore = 'high'
punctuation-dot = 'round'
digit-form = 'lining'

[buildPlans.iosevka-mayukai-firastorm.variants.italic]
a = 'single-storey-tailed'
f = 'tailed'
r = 'corner-hooked-base-serifed'

###################################################################################################
# Configure ligations

[buildPlans.iosevka-mayukai-firastorm.ligations]
inherits = "default-calt"
disables = []
enables  = [
    "center-ops",
    "arrow-l-hyphen",
    "arrow-r-hyphen",
    "arrow-lr-hyphen",
    "arrow-l-equal",
    "arrow-r-equal",
    "arrow-lr-equal",
    "trig",
    "eqeqeq",
    "eqeq",
    "lteq",
    "gteq",
    "exeqeq",
    "exeq",
    "brst",
    "plus-plus",
    "kern-dotty",
    "kern-bars",
    "logic",
    "llgg",
    "llggeq",
    "html-comment"
]

###################################################################################################
# Override default building weights
# Hanya build Regular, Medium, dan Bold

[buildPlans.iosevka-mayukai-firastorm.weights.regular]
shape = 400
menu  = 400
css   = 400

[buildPlans.iosevka-mayukai-firastorm.weights.medium]
shape = 500
menu  = 500
css   = 500

[buildPlans.iosevka-mayukai-firastorm.weights.bold]
shape = 700
menu  = 700
css   = 700

###################################################################################################
# Override default building slope sets

[buildPlans.iosevka-mayukai-firastorm.slopes.upright]
angle = 0
shape = "upright"
menu  = "upright"
css   = "normal"

[buildPlans.iosevka-mayukai-firastorm.slopes.italic]
angle = 9.4
shape = "italic"
menu  = "italic"
css   = "italic"

###################################################################################################
# Override default building widths
# Hanya build width Normal

[buildPlans.iosevka-mayukai-firastorm.widths.normal]
shape = 500
menu  = 5
css   = "normal"
